services:
  - type: web
    name: news-app
    env: node
    buildCommand: bash deploy.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLUTTER_VERSION
        value: stable
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false 