services:
  - type: web
    name: news-app
    env: node
    buildCommand: |
      flutter build web
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production 