services:
  - type: web
    name: news-app
    env: node
    buildCommand: "chmod +x deploy.sh && ./deploy.sh"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLUTTER_VERSION
        value: stable 