services:
  - type: web
    name: news-app
    env: node
    buildCommand: |
      npm install
      flutter build web --release
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 