services:
  - type: web
    name: news-app
    env: node
    buildCommand: |
      # Install Flutter
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter doctor
      flutter build web --release
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLUTTER_VERSION
        value: stable 